name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  Pipeline:
    name: Default
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate PROJECTKEY
      run: echo "REPOSITORY_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d "/" -f2)" >> $GITHUB_ENV

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=team-devopsport
          -Dsonar.projectKey=${{ env.REPOSITORY_NAME }}
          -Dsonar.qualitygate.wait=true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # - name: Run Snyk to check Kubernetes manifest file for issues
    #   run: |
    #     curl https://static.snyk.io/cli/latest/snyk-linux -o /usr/local/bin/snyk
    #     chmod +x /usr/local/bin/snyk
    #     snyk auth "${{ secrets.SNYK_TOKEN }}"
    #     snyk iac test --report --org="${{ secrets.SNYK_ORG }}" --severity-threshold=low --target-name="$(echo "${GITHUB_REPOSITORY}" | cut -d "/" -f2)"
